import { createFileRoute } from "@tanstack/react-router";
import { Compass, Eye, Heart, Lightbulb, Users } from "lucide-react";
import workshop from "@/assets/learning-workshop.jpg";
import { CtaBand, InfoCard, PageHero, SectionHeading } from "@/components/page-sections";

export const Route = createFileRoute("/about")({ head: () => ({ meta: seo("About Beyond Campaign", "Learn about our purpose, vision, mission, approach, and values for meaningful education.") }), component: About });
function seo(title:string, description:string){return [{title:`${title} — Beyond Campaign`},{name:"description",content:description},{property:"og:title",content:`${title} — Beyond Campaign`},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}
function About(){ return <><PageHero eyebrow="About us" title="Helping children understand the purpose of learning." text="Education becomes more meaningful when children understand not only what they learn, but also why they learn." />
<section className="px-5 py-20 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><img src={workshop} loading="lazy" width={1008} height={768} alt="Children participating in an interactive learning conversation" className="aspect-[4/3] w-full object-cover"/><div><SectionHeading eyebrow="Who we are" title="An educational awareness initiative." text="Beyond Campaign helps school-age children discover the purpose and value of learning. In a world full of information, children need opportunities to understand, think, question, apply, and learn from their experiences."/><h3 className="mt-8 text-2xl font-bold text-primary">Our approach</h3><p className="mt-3 leading-8 text-muted-foreground">We use simple conversations, activities, games, questions, stories, and real-life examples to make children think about learning.</p></div></div></section>
<section className="bg-ivory px-5 py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-5 md:grid-cols-2"><InfoCard icon={<Eye/>} title="Our Vision">To create a generation of children who value learning, think independently, ask questions, and use knowledge to build a better future.</InfoCard><InfoCard icon={<Compass/>} title="Our Mission">To spark an educational revolution by inspiring curious, thoughtful, and lifelong learners through awareness and experience.</InfoCard></div></div></section>
<section className="px-5 py-20"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="What guides us" title="Our values" center/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Curiosity","Ask questions and explore."],["Understanding","Value meaning over memorising."],["Thinking","Reason and form independent views."],["Learning","Embrace a continuous journey."],["Responsibility","Own personal learning and growth."],["Humanity","Use knowledge to help society."]].map(([t,d])=><InfoCard key={t} icon={<Lightbulb/>} title={t}>{d}</InfoCard>)}</div><div className="mt-16 border-y border-border py-10 text-center"><Users className="mx-auto text-gold-rich"/><h3 className="mt-4 text-3xl font-bold text-primary">Who we serve</h3><p className="mx-auto mt-3 max-w-2xl text-muted-foreground">School-age children, together with schools, parents, teachers, volunteers, and education supporters.</p></div></div></section><CtaBand title="When children know why, learning becomes their own." /></>}